### ISSUE TITLE
Building newlib failes

### ISSUE THREAD

**Issue by githubaf** [bebbo/amiga-gcc#96]
I tired compiling your latest commit from May, 5th and it aborts with newlib failed.

```
make gcc...done
install gcc...done
configure newlib...done
make newlib...failed
Making all in m68k
```

**Comment by bebbo** [comment]
https://travis-ci.org/bebbo/amiga-gcc says it's ok.

**Comment by spec-chum** [comment]
I suspect (s)he might be using MSYS2 as that fails in different places depending on the GCC you use.

Using /usr/bin/gcc fails on building newlib, as above, and using mingw32/bin/gcc fails in building GCC.

I've forgotten the exact errors to be honest, but I seem to remember the newlib one is an ld error, and the gcc build error is to do with readlink.

I just use cygwin64 now, where it builds first time.  Takes a while tho.

**Comment by bebbo** [comment]
is building with cygwin and msys2

**Comment by githubaf** [comment]
I just retried again.
04.May was compileable.
05.May failed.

I always try with a completely new git clone into a new directory. Ubuntu 16.4

**Comment by bebbo** [comment]
maybe and quite possibly some relevant log could help?

**Comment by bebbo** [comment]
> I always try with a completely new git clone into a new directory. Ubuntu 16.4

also a fresh repo folder? Try killing the sys-include folder.

**Comment by githubaf** [comment]
I did no see much in the output. I use a script that checks out to the latest commits of a certein date and then builds. Can I enable more output?

[compile.txt.gz](https://github.com/bebbo/amiga-gcc/files/3148282/compile.txt.gz)

**Comment by bebbo** [comment]
if the build failes it always prints, what to look at:

```
less "log/make newlib.log"
```

**Comment by bebbo** [comment]
using an absolute path might help, e.g. `cd /c/msys64/home/test/amiga-gcc` then `make clean-newlib` and continue your build

**Comment by githubaf** [comment]
Here is the logfile.
[make newlib.log.gz](https://github.com/bebbo/amiga-gcc/files/3152280/make.newlib.log.gz)

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

Btw, building the last commit from yesterday (6.May) worked again. Did you fix anything?
Retried 05.May, that still failes.

**Comment by bebbo** [comment]
"/home/developer/amiga-gcc_05May19/projects/newlib-cygwin/newlib/libc/stdlib/__call_atexit.c: In function '__call_exitprocs':
/home/developer/amiga-gcc_05May19/projects/newlib-cygwin/newlib/libc/stdlib/__call_atexit.c:166:1: internal compiler error: Segmentation fault"

Hm, that was already fixed and never went from develop1 to gcc-6-branch without the fix.

`make update` ?

**Comment by spec-chum** [comment]
> using an absolute path might help, e.g. `cd /c/msys64/home/test/amiga-gcc` then `make clean-newlib` and continue your build

Hey cool, this worked.  Still fails on building gcc using mingw32 or mingw64 tho, only builds with /usr/bin/gcc

**Comment by githubaf** [comment]
>develop1 may fail every now and then. Merging is done, if the build was successful and the checks are passed.

I see and do fully understand. Your work is very much appreciated!

Lets just close it.
